run:
  # timeout for analysis, e.g. 30s, 3m, default is 1m
  timeout: 3m
  # exclude test files
  tests: false

linters:
  disable-all: false
  enable:
    # bugs/error
    - staticcheck
    - gosec
    - errcheck
    - govet

    # performance
    - prealloc

    # style, formatting
    - gofmt
    - goconst
    - unconvert
    - misspell
    - unparam # 检测未使用的函数参数
    - nakedret # 检查裸返回
    - tagliatelle # 检查 struct tag 格式
    - ineffassign
    - revive
    - dupl

linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'

  misspell:
    locale: US

  errcheck:
    check-type-assertions: true
  dupl:
    # Tokens count to trigger issue, Default: 150
    threshold: 100
  govet:
    enable:
      - atomic
      - bools
      - nilfunc
      - printf
    disable:
      - unreachable

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: false
  exclude:
    # gosec: Duplicated errcheck checks
    - G104
    - "undefined: cli"                         # 忽略 cli 未定义错误
    - "could not import sync/atomic"
